#:schema node_modules/wrangler/config-schema.json
name = "butler-email-router-prod"
main = "src/index.ts"
compatibility_date = "2024-04-21"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[vars]
# Production variables will be set through Cloudflare dashboard or GitHub Actions secrets

[[send_email]]
name = "SEND_EMAIL"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "email_storage"
database_id = "<unique-ID-for-your-database>"